image: smblott/dcu-docker-gitlab-ci:latest

run:
  script:
    - python3 -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python3 -m twine upload --repository-url  ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
